openapi: '3.0.1'
info:
  title: User
  version: "1"
  description: User Resources

servers:
  - url: http://localhost:8080/api
    description: Local server

paths:
  /user:
    post:
      summary: Save User
      operationId: saveUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'

components:
  schemas:
    UserDTO:
      type: object
      description: Data element for user
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        firstName:
          type: string
          minLength: 3
          maxLength: 10
        lastName:
          type: string
